Issue 3: COMPILATION ERROR: Cannot find PreInsert
PreInsert annotation reflects which method to call before a new record is added. Similarly PrePersist does the name. Thus ```java @PreInsert``` was replaced by ```java @PrePersist``` giving the same results